SU-SWS/stanford_person

- stanford_person.strongarm.inc
Change ANT strongarm variable to use entity tokens instead of core tokens.
@jbickar: Your problem now.
> Changed ANT to use entity tokens

- stanford_person.views_default.inc
Added new exposed filter for author to manage display.
> Vpsadev 146

- stanford_person.field_group.inc
- stanford_person.views_default.inc
this commit included changes done on vpsadev-240 branch
> Vpsadev 257

- modules/stanford_person_views/stanford_person_views.views_default.inc
This adds and updates the sort by taxonomy weight for most of the views.
> SOE-623: Updated tax weight for grouping views

- modules/stanford_person_views/stanford_person_views.views_default.inc
Okay, @sherakama, I removed the rewrite with the h2.
> Basic 2008

- stanford_person.features.field_base.inc
@cjwest @jbickar @boznik @tsui1 FYI
> SOE-658: Removed default image file id so it doesn't get set unintentionally 

- stanford_person.install
> SOE-844: added array()

- stanford_person.install
To indicate what it actually does
> Update docblock for update_7501

- modules/stanford_person_views/stanford_person_views.views_default.inc
> HSDO-608: Added alumni views

- README.md
- config/optional/metatag.metatag_defaults.node__stanford_person.yml
- config/optional/metatag.metatag_defaults.page_variant__stanford_person_list-layout_builder-1.yml
- config/optional/rabbit_hole.behavior_settings.node_type_stanford_person.yml
- config/optional/xmlsitemap.settings.node.stanford_person.yml
- config/optional/xmlsitemap.settings.taxonomy_term.stanford_person_types.yml
- Added optional configs to enable metatag and xmlsitemap support if the modules are available
- tomorrow
- medium
1. nothing to test.
> added xmlsitemap and metatag configs for optional

- tests/codeception/acceptance/StanfordPersonCest.php
- Codeception tests
- Today
- 10
- Let the robots do their thing
- Review test code.
> D8CORE-1969: Codeception Tests For Person

- stanford_person.info.yml
> back to dev

- config/install/views.view.stanford_person_terms.yml
- A11y fix for a span wrapping a div.
- Thursday
- Med
- Core, person module
2. Navigate to a filtered person page. You might need to add Haley our sample to a taxonomy term.
3. Verify the top description of "Faculty ... text" is not wrapped in a span tag. 
- Person Module
- Accessibility
- D8CORE-2007
- https://github.com/SU-SWS/stanford_profile/pull/249
- A11y fix
- @cjwest 
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/Ext …
> D8CORE-2007: removing the span as a wrapper

- composer.json
- tests/codeception/acceptance/StanfordPersonCest.php
- Cherry picks `8280ca29edf819141eec72bf7a6bc42d976da818` from #99 
- Resolves https://www.drupal.org/project/view_unpublished/issues/3153470
- By next release
- Medium/Low
2. Install `standard` profile 
3. Enable this module
4. Run tests
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)
> DEVOPS-000: view_unpublished needs to be at dev version or tests fail.

- composer.json
- Removed unused dependency
- 
- 
> Removed views_taxonomy_term_name_depth thats not used

- CHANGELOG.md
- composer.json
- config/install/views.view.stanford_person_list_terms_first.yml
- modules/stanford_person_importer/src/Cap.php
- modules/stanford_person_importer/stanford_person_importer.info.yml
- modules/stanford_person_importer/tests/src/Unit/CapTest.php
- stanford_person.info.yml
- Automated pull request created via HAL 9000.  See changes below for details.
- As soon as possible
The following changes since commit a3d82884169084e3415725fc2388705f1494528b:
Merge pull request #104 from SU-SWS/release-8.1.4 (2020-08-07 13:37:48 -0600)
are available in the Git repository at:
./ 
for you to fetch changes up to d1ca182d23e6db3938ce38fe5609875f1504c4d2:
8.1.5 (2020-09-09 15:25:44 -0600)
----------------------------------------------------------------
Ian Monroe (1):
8.1.5
Sherakama (1):
D8CORE-2535: Change sort on interior pages to be by last name first (#107)
pookmish (2):
D8CORE-2499 Updated composer license (#105)
D8CORE-000 Adjusted regext to retain numbers in workgroups and org codes (#106)
sws-developers@lists.stanford.edu (1):
Back to dev
CHANGELOG.md …
> "8.x-1.x >  8.1.5

- config/install/core.entity_form_display.node.stanford_person.default.yml
- config/install/core.entity_form_display.taxonomy_term.stanford_person_types.default.yml
- config/install/core.entity_view_display.node.stanford_person.default.yml
- config/install/core.entity_view_display.node.stanford_person.teaser.yml
- config/install/field.field.node.stanford_person.su_person_academic_appt.yml
- config/install/field.field.node.stanford_person.su_person_admin_appts.yml
- config/install/field.field.node.stanford_person.su_person_scholarly_interests.yml
- config/install/field.storage.node.su_person_academic_appt.yml
- config/install/field.storage.node.su_person_admin_appts.yml
- config/install/field.storage.node.su_person_scholarly_interests.yml
- modules/stanford_person_importer/config/install/migrate_plus.migration.su_stanford_person.yml
- Added 3 fields and map 4 fields to the API
- see https://github.com/SU-SWS/stanford_profile/pull/294
- 9/21
- low
- see https://github.com/SU-SWS/stanford_profile/pull/294
> CAP-52 Map 4 more fields from cap API

- config/install/views.view.stanford_person.yml
- Changes to the two person views are to wrap the photo and the title (person's name) in a single <a>
- v1.5
Addresses accessibility issues
- How critical is this PR on a 1-10 scale? 1 - Addresses accessibility issues (https://stanfordits.atlassian.net/browse/D8CORE-1705).
- It affects every site using D8Core
There are two views involved.
2. Navigate to the person list page, i.e. `/people`
1. Verify that for each profile, both the title and the image are linked in the same `<a>`
1. Navigate to a taxonomy term page, 1.e. `/people/faculty`
1. Verify that for each profile, both the title and the image are linked in the same `<a>`
- [ √] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ √] Cross-browser testing has been performed? - …
> D8CORE-2349: updating person list view to a single link

- modules/stanford_person_importer/tests/src/Unit/CapTest.php
- Updated phpunit tests so they will pass on phpunit 8 with drupal 9
- whenever
- low
> Update tests for D9 phpunit

- modules/stanford_person_importer/config/install/core.entity_form_display.config_pages.stanford_person_importer.default.yml
- modules/stanford_person_importer/config/install/core.entity_view_display.config_pages.stanford_person_importer.default.yml
- modules/stanford_person_importer/config/install/field.field.config_pages.stanford_person_importer.su_person_child_orgs.yml
- modules/stanford_person_importer/config/install/field.storage.config_pages.su_person_child_orgs.yml
- modules/stanford_person_importer/src/Config/ConfigOverrides.php
- Added checkbox to include child organizations 
- ASAP
- high
1. Follow the steps in https://github.com/SU-SWS/stanford_profile/pull/381
> Add "include child orgs" checkbox for cap org importer

- modules/stanford_person_importer/config/install/migrate_plus.migration.su_stanford_person.yml
- modules/stanford_person_importer/src/Cap.php
- modules/stanford_person_importer/tests/src/Unit/CapTest.php
- Fixed the parameter string for sunet importing.
- asap
- high
> Fixed cap API parameter string

- templates/block/block--menu-block--person-type.html.twig
- Added the skip to secondary nav
- June 26
- Med
- Accessibility
- Events
- News
- People
- medium
1. Check out this branch and the related pull request
2. Rebuild Cache and import config `drush cr ; drush ci`
3. Make sure you have news, people, publications, event series, past events and events
4. Verify you can use the skip to links for both the secondary navigation and the main content well.  
5. This change is big and must be reviewed by @cjwest 
- Is there a config:export in this PR that changes the config sync directory?
- Does this PR impact any particular projects, products, or modules?
- [D8CORE-4378](https://stanfordits.atlassian.net/browse/D8CORE-4378)
- https://github.com/SU-SWS/stanford_news/pull/127
- https://github.com/SU-SWS/stanford_person/pull/145
- …
> D8CORE-4378: adding the skip to secondary link on person

- templates/block/block--menu-block--person-type.html.twig
- Adding the Skip to Main on the topics menu for Events, News, and People. Publications is in a different pull request.
- 7/6
- Effects SBT
- and Subthemes
- Med
2. Rebuild Cache and import config `drush cr ; drush ci`
3. Navigate to /person
4. Verify you can tab to the skip to main link on the topics menu. 
5. Navigate to /person filtered page 
6. Verify you can tab to the skip to main link on the topics menu. 
- Is there a config:export in this PR that changes the config sync directory? NO
- Event Module
- Person Module
- News Module
- [D8CORE-4508](https://stanfordits.atlassian.net/browse/D8CORE-4508)
- https://github.com/SU-SWS/stanford_news/pull/128
- https://github.com/SU-SWS/stanford_events/pull/77
- @cjwest 
- [AMP …
> D8CORE-4508: adding skip to main on the topic menu

- composer.json
- (Edit the above to reflect status)
- TL;DR - what's this PR for?
- When does this need to be reviewed by?
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?
- How urgent is this? (Normal, High)
2. Rebuild Cache and import config `drush cr ; drush ci`
3. Navigate to...
4. Verify...
- Is there a config:export in this PR that changes the config sync directory?
- Does this PR impact any particular projects, products, or modules?
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? …
> Updated views_infinite_scroll module
